# version: '3.8'

# services:
#   api:
#     build: .
#     ports:
#       - 4000:4000
#     environment:
#       DB_URL: mongodb://db/songs
#     volumes:
#       - :/app
#     depends_on:
#       - db
#     command: ./docker-entrypoint.sh
#   db:
#     image: mongo:latest
#     ports:
#       - 27017:27017
#     volumes:
#       - songs:/data/db

# volumes:
#   songs:

version: '3'
services:
  mongo:
      image: mongo:latest
      restart: always
      volumes:
        - songs:/data/db
  app:
    build: .
    ports:
      - 4000:4000
    environment:
        MONGO_URI: mongodb://mongo:27017/songs_db
        PORT: 4000
    depends_on:
      - mongo

volumes:
  songs: