# version: '3.8'

# services:
#   api:
#     build: .
#     ports:
#       - 4000:4000
#     environment:
#       DB_URL: mongodb://db/songs
#     volumes:
#       - :/app
#     depends_on:
#       - db
#     command: ./docker-entrypoint.sh
#   db:
#     image: mongo:latest
#     ports:
#       - 27017:27017
#     volumes:
#       - songs:/data/db

# volumes:
#   songs:

version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  nodejs:
    container_name: nodejs
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    links:
      - mongodb
volumes:
  mongodb_data:
    driver: local
