const SONG_FETCH_REQUESTED="SONG_FETCH_REQUESTED"
const UPDATE_SONG_REQUESTED = "UPDATE_SONG_REQUESTED"
const CREATE_SONG_REQUESTED = "CREATE_SONG_REQUESTED"
const REMOVE_SONG_REQUESTED = "REMOVE_SONG_REQUESTED"

const SONG_FETCH_SUCCESS = "SONG_FETCH_SUCCESS"
const UPDATE_SONG_SUCCESS = "UPDATE_SONG_SUCCESS"
const CREATE_SONG_SUCCESS = "CREATE_SONG_SUCCESS"
const REMOVE_SONG_SUCCESS = "REMOVE_SONG_SUCCESS"

const SONG_FETCH_FAILED = "SONG_FETCH_FAILED"
const UPDATE_SONG_FAILED = "UPDATE_SONG_FAILED"
const CREATE_SONG_FAILED = "CREATE_SONG_FAILED"
const REMOVE_SONG_FAILED = "REMOVE_SONG_FAILED"


export {
    SONG_FETCH_REQUESTED,
    UPDATE_SONG_REQUESTED,
    CREATE_SONG_REQUESTED,
    REMOVE_SONG_REQUESTED,
    SONG_FETCH_SUCCESS,
    UPDATE_SONG_SUCCESS,
    CREATE_SONG_SUCCESS,
    REMOVE_SONG_SUCCESS,
    SONG_FETCH_FAILED,
    UPDATE_SONG_FAILED,
    CREATE_SONG_FAILED,
    REMOVE_SONG_FAILED
}